import "@hotwired/turbo-rails";
import { Application } from "@johanhalse/musculus";

import AdminCleaveController from "./controllers/admin_cleave_controller";
import AdminTabController from "./controllers/admin_tab_controller";
import BackToScopeController from "./controllers/back_to_scope_controller";
import BatchActionController from "./controllers/batch_action_controller";
import ClickableRowController from "./controllers/clickable_row_controller";
import CommissionCalculatorController from "../../../highway/app/javascript/admin/commission_calculator_controller";
import DatetimeSelectController from "./controllers/hamburger_menu_controller";
import DraggableController from "../../../highway/app/javascript/admin/draggable_controller";
import GeoSearchController from "./controllers/geo_search_controller";
import GlobalSearchController from "../../../highway/app/javascript/admin/global_search_controller";
import HamburgerMenuController from "./controllers/datetime_select_controller";
import ImagePreviewController from "./controllers/image_preview_controller";
import LeadDialogController from "../../../highway/app/javascript/admin/lead_dialog_controller";
import LeadFiltersController from "../../../highway/app/javascript/admin/lead_filters_controller";
import LeadGroupController from "../../../highway/app/javascript/admin/lead_group_controller";
import LeafletController from "../../../highway/app/javascript/admin/leaflet_controller";
import PastClosedAtController from "../../../highway/app/javascript/admin/past_closed_at_controller";
import RelationSearchController from "./controllers/relation_search_controller";
import ReserveGuardController from "../../../highway/app/javascript/admin/reserve_guard_controller";
import RichTextEditorController from "./controllers/rich_text_editor_controller";
import SelectAllController from "./controllers/select_all_controller";
import SlugonatorController from "./controllers/slugonator_controller";
import TagFieldController from "./controllers/tag_field_controller";
import ToggleFormsController from "../../../highway/app/javascript/admin/toggle_forms_controller";

Application.register(AdminCleaveController);
Application.register(AdminTabController);
Application.register(BackToScopeController);
Application.register(BatchActionController);
Application.register(ClickableRowController);
Application.register(CommissionCalculatorController);
Application.register(DatetimeSelectController);
Application.register(DraggableController);
Application.register(GeoSearchController);
Application.register(GlobalSearchController);
Application.register(HamburgerMenuController);
Application.register(ImagePreviewController);
Application.register(LeadDialogController);
Application.register(LeadFiltersController);
Application.register(LeadGroupController);
Application.register(LeafletController);
Application.register(PastClosedAtController);
Application.register(RelationSearchController);
Application.register(ReserveGuardController);
Application.register(RichTextEditorController);
Application.register(SelectAllController);
Application.register(SlugonatorController);
Application.register(TagFieldController);
Application.register(ToggleFormsController);
Application.start();
